### ISSUE TITLE
try and dump

### ISSUE THREAD

**Issue by xiaozhi12345678** [jiawei-mo/scale_optimization#1]
Hello,I download the project and try it with MH_05 dataset, but after it run just a second the core dump comes.Is it the same as you?

**Comment by xiaozhi12345678** [comment]
the core dump happend after INITIALIZE FROM INITIALIZER (1988 pts)!,could you please run it ,thanks!

**Comment by xiaozhi12345678** [comment]
![github](https://user-images.githubusercontent.com/38774561/71307511-6d590b80-242a-11ea-9edb-c5b1712c3991.png)
as this

**Comment by jiawei-mo** [comment]
If it only failed on MH05, try to skip the starting part of MH05 where is drone is flying up down and looking at very close objects (e.g. the wood platform). These cases are too challenging for the initialization of scale optimization (i.e. find an initial scale in a brute-force way). 
The code works on my machine but fails to initialize the scale. If I skip the first fart of MH5 (starting at 1403638541.161524(about 23s) in my case), the system runs smoothly.

**Comment by xiaozhi12345678** [comment]
thank you,I try it again but it also.I found that on other dataset it also cannot run.Maybe the question is my computer,anyway thank you very much!

**Comment by jiawei-mo** [comment]
Thanks for trying. Let me know if there is any further question.

**Comment by xiaozhi12345678** [comment]
I am sorry forgetting ask you a question.What the environment you run the code,I mean the hard ware and soft ware,thank you!

**Comment by jiawei-mo** [comment]
Intel PC, Ubuntu 18.04.
