### ISSUE TITLE
scale_accept_th

### ISSUE THREAD

**Issue by xiaozhi12345678** [jiawei-mo/scale_optimization#2]
hello，can you tell me how to set scale_accept_th,I see you set it to 10 or 20,why?Thank you!

**Comment by jiawei-mo** [comment]
Take a look at https://github.com/jiawei-mo/scale_optimization/blob/master/src/ScaleOptimizer.cpp#L216. 
The scale_accept_th is the photometric error threshold for scale optimization to accept the result. You can print out lastResiduals[0] in your use-case and decide a threshold.
