### ISSUE TITLE
results file

### ISSUE THREAD

**Issue by xiaozhi12345678** [jiawei-mo/scale_optimization#3]
Hello,Would you please give your results files on euroc or kitti datasets contain no loop-closure and loop-closure?Or maybe you don't have all files,but if you have some files,thats ok. I am really need them,thank you very much！

**Comment by jiawei-mo** [comment]
Sure, I will try to find them. May I have your email if I can find them.

**Comment by xiaozhi12345678** [comment]
Thank you very much，and my email is 756068139@qq.com.



---Original---
