### ISSUE TITLE
How to calculate Jacobian

### ISSUE THREAD

**Issue by ShrutheeshIR** [jiawei-mo/scale_optimization#6]
Hello.
Thanks for sharing the work! I am trying to recreate the scale optimization in Matlab, to integrate into our Visual Odometry system. Could you point out the Jacobian calculation in the code? I checked out ScaleOptimizer and ScaleAccumulator, but could not find where and how the Jacobians are calculated (nor the reprojection errors, though implementing that is quite trivial)  I did go through the paper, and seem to be stuck at finding Jacobians. 

From what I could gather, for a given 3D point, the Jacobian in the y direction is the image gradient in the y direction times the ∂Π / ∂s in the 'y' direction. Similarly the values are found for the 'x' direction, and finally, are they added together, i.e. is Js the sum of Jacobian components in the x and y direction? These Js values are found for every point and finally, and using a Gauss Newton step, the scale increment is found.

Could you please elaborate on finding the Jacobian? (preferably with a tiny example)

I'm not entirely sure if this issue belongs here, so please feel free to delete it if inappropriate.
Thanks!

**Comment by jiawei-mo** [comment]
Hi,

Thank you for being interested in this project. The Jacobians are located in [ScaleOptimizer.cpp](https://github.com/jiawei-mo/scale_optimization/blob/master/src/ScaleOptimizer.cpp#L413). The code is modified from DSO with SSE instructions, so the readability is not good (apologies for that).

The Jacobians in the paper is much clear. At a high level, it is the image gradient and then the projection by scale. I think your understanding is correct. 

To calculate the Jacobians, you simply find the image gradient [du dv], then calculate ∂Π / ∂s; then you get the Jacobian of the pixel intensity w.r.t. scale as [du dv] * ∂Π / ∂s. 

If your images are stereo-rectified, you can simplify the  ∂Π / ∂s: [x', y', z'] = [x, y, z] the point position; tx is the baseline, ty=tz=0.

Please let me know for further questions.

Best,
Jiawei

**Comment by ShrutheeshIR** [comment]
Fantastic! Thanks for the quick reply. 
By [du dv] * ∂Π / ∂s, do you mean a simple dot product ? (since ∂Π / ∂s has two components, one of which is 0 since ty is zero which means the value is merely du * 'x' component of ∂Π / ∂s), or are both 'du' and the 'dv' components multiplied by the 'x' term of the ∂Π / ∂s ? 

To be more clear, say, ∂Π / ∂s = [p, q]. Then is the Jacobian of the pixel intensity 
Js = p * du + q * dv ---------(1) 
or, is 
Js = p * du + p * dv + q * du + q * dv -------- (2)

This is the tiny part where I am unclear.

Thanks!

**Comment by jiawei-mo** [comment]
It is a dot product, eq. (1). For the stereo-rectified case, 'dv' is multiplied by zero.

**Comment by ShrutheeshIR** [comment]
Hi @jiawei-mo 
Thanks. It works!
